Repository EVerest/libevse-security, pull requests merged in 2024-02, with the labels that each got.

#28 Make test target name unique.
  CMakeLists.txt
  README.md
  tests/CMakeLists.txt
Labels: testing

#25 ci: Run tests in CI
  .ci/build-kit/install_and_test.sh
  .github/workflows/build_and_test.yaml
  .github/workflows/lint.yaml
  .gitignore
  README.md
Labels: CI/CD, testing

#39 Added cleanup/certificate limit features:
  include/evse_security/certificate/x509_bundle.hpp
  include/evse_security/certificate/x509_wrapper.hpp
  include/evse_security/evse_security.hpp
  lib/evse_security/certificate/x509_bundle.cpp
  lib/evse_security/evse_security.cpp
  tests/CMakeLists.txt
  tests/tests.cpp
Labels: enhancement

#44 Garbage collect routines with:
  CMakeLists.txt
  dependencies.yaml
  include/evse_security/evse_security.hpp
  lib/evse_security/CMakeLists.txt
  lib/evse_security/evse_security.cpp
  tests/tests.cpp
Labels: enhancement

#47 Tests for expired certificates, fixes for expired key deletion
  include/evse_security/evse_security.hpp
  lib/evse_security/evse_security.cpp
  tests/CMakeLists.txt
  tests/expired_runtime/conf.cnf
  tests/tests.cpp
Labels: bug, testing

#56 Removed strict cert verification, added error string print
  lib/evse_security/crypto/openssl/openssl_supplier.cpp
Labels: bug
